# Generated by Django 6.0.7 on 2026-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='institution_type',
            field=models.CharField(choices=[('university', 'University'), ('polytechnic', 'Polytechnic'), ('college_of_education', 'College of Education'), ('college_of_health', 'College of Health Sciences/Technology'), ('technical', 'Technical/Vocational College'), ('other', 'Other institution')], default='university', max_length=25),
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(default='Nigeria', max_length=120),
        ),
    ]
