# Generated by Django 6.0.7 on 2026-07-14 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def blank_phones_to_null(apps, schema_editor):
    # Multiple '' values would violate the new unique constraint.
    apps.get_model("accounts", "User").objects.filter(phone="").update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_normalize_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(blank_phones_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
