# Generated by Django 6.0.7 on 2026-07-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_phone_verified_alter_user_phone_phoneotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
