# Generated by Django 6.0.7 on 2026-07-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canonical_email',
            field=models.EmailField(editable=False, max_length=254, null=True, unique=True),
        ),
    ]
